In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [88]:
netflix_data = pd.read_csv('NetFlix.csv')
netflix_data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

### Checking the data information,non-null count and datatype

In [89]:
netflix_data.shape  #How many rows and columns are there in this dataset

(7787, 12)

In [90]:
netflix_data.columns #SHows the column list

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'genres', 'description'],
      dtype='object')

In [91]:
netflix_data.info() #shows information about datatype and non-null

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

In [92]:
netflix_data.describe()

       release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

#### Finding the sum of null values in each column

In [93]:
netflix_data.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

In [94]:
netflix_data.duplicated().sum()

np.int64(0)

In [95]:
netflix_data.loc[netflix_data.duplicated()] #There are no duplicated columns.

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, genres, description]
Index: []

In [96]:
netflix_data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s995,TV Show,Blown Away,NaN,NaN,Canada,12-Jul-19,2019,TV-14,1,"International TV Shows, Reality TV",Ten master artists turn up the heat in glassbl...
7783,s996,TV Show,Blue Exorcist,NaN,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Japan,1-Sep-20,2017,TV-MA,2,"Anime Series, International TV Shows",Determined to throw off the curse of being Sat...
7784,s997,Movie,Blue Is the Warmest Color,Abdellatif Kechiche,"Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...","France, Belgium, Spain",26-Aug-16,2013,NC-17,180,"Dramas, Independent Movies, International Movies","Determined to fall in love, 15-year-old Adele ..."
7785,s998,Movie,Blue Jasmine,Woody Allen,"Cate Blanchett, Sally Hawkins, Alec Baldwin, L...",United States,8-Mar-19,2013,PG-13,98,"Comedies, Dramas, Independent Movies",The high life leads to high anxiety for a fash...
7786,s999,Movie,Blue Jay,Alex Lehmann,"Sarah Paulson, Mark Duplass, Clu Gulager",United States,6-Dec-16,2016,TV-MA,81,"Dramas, Independent Movies, Romantic Movies",Two former high school sweethearts unexpectedl...

In [97]:
netflix_data=netflix_data[['cast','director','country']].fillna('Not Specified')
netflix_data

,cast,director,country
0,"João Miguel, Bianca Comparato, Michel Gomes, R...",Not Specified,Brazil
1,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",Vikram Bhatt,India
2,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Iman Brotoseno,Indonesia
3,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",Lev L. Spiro,United States
4,David Attenborough,Not Specified,United Kingdom
...,...,...,...
7782,Not Specified,Not Specified,Canada
7783,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Not Specified,Japan
7784,"Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...",Abdellatif Kechiche,"France, Belgium, Spain"
7785,"Cate Blanchett, Sally Hawkins, Alec Baldwin, L...",Woody Allen,United States
7786,"Sarah Paulson, Mark Duplass, Clu Gulager",Alex Lehmann,United States

In [98]:
netflix_data.loc[
    (netflix_data[["director", "cast", "country"]] == "Not Specified").any(
        axis=1
    )
]

,cast,director,country
0,"João Miguel, Bianca Comparato, Michel Gomes, R...",Not Specified,Brazil
4,David Attenborough,Not Specified,United Kingdom
9,Not Specified,Barry Avrich,Canada
10,"Sumire Morohoshi, Yoshimasa Hosoya, Maria Naga...",Not Specified,Japan
11,Not Specified,Nawapol Thamrongrattanarit,Thailand
...,...,...,...
7777,"Guilherme Fontes, Ravel Cabral, Jonathan Haage...",Not Specified,Brazil
7779,"Kyle Chandler, Ben Mendelsohn, Sissy Spacek, L...",Not Specified,United States
7780,"Ine Marie Wilmann, Bjørnar Teigen, Emma Spetal...",Not Specified,Norway
7782,Not Specified,Not Specified,Canada
7783,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Not Specified,Japan

In [99]:
netflix_data.loc[
    (netflix_data["director"] == "Not Specified")|
    (netflix_data["country"] == "Not Specified")|
    (netflix_data["cast"] == "Not Specified")
    
]

,cast,director,country
0,"João Miguel, Bianca Comparato, Michel Gomes, R...",Not Specified,Brazil
4,David Attenborough,Not Specified,United Kingdom
9,Not Specified,Barry Avrich,Canada
10,"Sumire Morohoshi, Yoshimasa Hosoya, Maria Naga...",Not Specified,Japan
11,Not Specified,Nawapol Thamrongrattanarit,Thailand
...,...,...,...
7777,"Guilherme Fontes, Ravel Cabral, Jonathan Haage...",Not Specified,Brazil
7779,"Kyle Chandler, Ben Mendelsohn, Sissy Spacek, L...",Not Specified,United States
7780,"Ine Marie Wilmann, Bjørnar Teigen, Emma Spetal...",Not Specified,Norway
7782,Not Specified,Not Specified,Canada
7783,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Not Specified,Japan

In [100]:
netflix_data.loc[(netflix_data[['director','cast','country']]=='Not Specified').all(axis=1)].count()

cast        58
director    58
country     58
dtype: int64

In [1]:
pwd

'C:\\Users\\Dell\\projects\\netflix_data_analysis'

In [3]:
cd ..

C:\Users\Dell\projects

In [4]:
!git init

Initialized empty Git repository in C:/Users/Dell/projects/.git/

In [ ]:
!git ad